# RSA signing keypair for RS256 JWTs. The private key is generated by
# Terraform and therefore present in the state — run this only with an
# encrypted remote state backend.
resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = var.rsa_bits
}

locals {
  kid = substr(sha256(tls_private_key.this.public_key_pem), 0, 16)
}

resource "aws_secretsmanager_secret" "this" {
  name                    = var.name
  description             = "RS256 JWT signing key (private key PEM + kid)."
  kms_key_id              = var.kms_key_id
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "this" {
  secret_id = aws_secretsmanager_secret.this.id
  secret_string = jsonencode({
    privateKeyPem = tls_private_key.this.private_key_pem
    kid           = local.kid
  })
}
